# Generated by Django 5.2.6 on 2026-03-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_license_number_user_parent_owner_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily milk quantity in liters', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='milk_type',
            field=models.CharField(blank=True, choices=[('cow', 'Cow'), ('buffalo', 'Buffalo'), ('both', 'Both')], max_length=20, null=True),
        ),
    ]
