# Generated by Django 5.2.6 on 2026-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_daily_quantity_user_milk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dairy_name',
            field=models.CharField(blank=True, help_text='For Owner users', max_length=100, null=True),
        ),
    ]
