# Generated by Django 5.2.6 on 2026-03-11 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_dairy_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Assigned Driver for this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_route', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Assigned route for Customers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.route'),
        ),
    ]
