# Generated by Django 5.2.6 on 2026-03-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delivery_status_deliveryadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('pause', 'Pause Delivery'), ('quantity', 'Change Quantity'), ('complaint', 'Complaint')], max_length=20),
        ),
    ]
