# Generated by Django 5.2.6 on 2026-03-18 09:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_delivery_price_at_delivery_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryadjustment',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='owner',
            new_name='invited_by',
        ),
        migrations.AlterUniqueTogether(
            name='deliveryadjustment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='route',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='token',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
        migrations.AddField(
            model_name='delivery',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('customer', 'Customer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='outstanding_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.route'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='deliveryadjustment',
            index=models.Index(fields=['customer', 'date'], name='accounts_de_custome_d53c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryadjustment',
            index=models.Index(fields=['status'], name='accounts_de_status_a02e22_idx'),
        ),
    ]
