# Generated by Django 5.2.6 on 2026-03-18 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_deliveryadjustment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dairy_name',
            field=models.CharField(blank=True, help_text='For Owner users', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Dairy Name must only contain alphabets and spaces.', regex='^[a-zA-Z\\s]+$')]),
        ),
    ]
