# Generated by Django 5.2.6 on 2026-03-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
