# Generated by Django 5.2.6 on 2026-03-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_invitation_expires_at_invitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
