# Generated by Django 5.2.6 on 2026-03-25 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
