# Generated by Django 5.2.6 on 2026-03-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_latitude_alter_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sequence_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
