# Generated by Django 5.2.6 on 2026-03-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='total_customers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
